version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
    environment:
      POSTGRES_DB: deeplink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  api:
    build:
      context: Deeplink
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/deeplink
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_SHOW-SQL: true
      SPRING_HIBERNATE_DDL-AUTO: update
  tgbot:
    build:
      context: DeeplinkBot
      dockerfile: Dockerfile
    depends_on:
      api:
        condition: service_healthy

